export const statusLabels: Record<string, string> = {
  DRAFT: "Borrador",
  INITIAL_VALIDATION: "En validacion inicial",
  FORMAT_OBSERVED: "Observada por formato",
  ALIGNMENT_REJECTED: "Rechazada por alineacion",
  REGISTERED: "Registrada",
  CLASSIFIED: "Clasificada",
  IMPACT_ANALYSIS: "En analisis de impacto",
  FAST_APPROVAL: "En aprobacion rapida",
  CCB_REVIEW: "En revision CCB",
  APPROVED: "Aprobada",
  REJECTED: "Rechazada",
  RESOURCE_ASSIGNMENT: "En asignacion",
  IMPLEMENTATION: "En implementacion",
  UNIT_TESTING: "En pruebas unitarias",
  QA_TESTING: "En pruebas QA",
  QA_DEFECTS: "Con defectos QA",
  UAT: "En UAT",
  UAT_OBSERVATIONS: "Con observaciones UAT",
  UAT_ACCEPTED: "Aceptada por UAT",
  INTEGRATION: "En integracion",
  FINAL_VALIDATION: "En validacion final",
  RELEASE_APPROVED: "Release aprobado",
  RELEASED: "Liberada",
  ARCHIVED: "Archivada",
  CLOSED: "Cerrada",
  ACTIVE: "Activo",
  INACTIVE: "Inactivo",
  PAUSED: "Pausado",
  AVAILABLE: "Disponible",
  LOCKED: "Bloqueado",
  BASELINED: "En linea base",
  FROZEN: "Congelada",
  OPEN: "Abierta",
  ASSIGNED: "Asignada",
  IN_PROGRESS: "En progreso",
  DERIVED_TO_CHANGE: "Derivada a cambio",
  RESOLVED: "Resuelta",
  CHECKED_IN: "Check-in",
  RELEASED_LOCK: "Liberado",
  FORCED: "Forzado",
  COMPLETED: "Completada",
  PENDING: "Pendiente",
  SUBMITTED: "Subida",
  QA_APPROVED: "Aprobada por QA",
  QA_REJECTED: "Rechazada por QA",
  WAIVED: "Exceptuada",
  PASSED: "OK",
  FAILED: "Fallida",
  ACCEPTED: "Aceptada",
  OBSERVED: "Observada",
  READY_FOR_QA: "Listo para QA",
  READY_FOR_UAT: "Listo para UAT",
  READY_FOR_INTEGRATION: "Listo para integracion",
  INTEGRATED: "Integrada",
  CANCELLED: "Cancelada",
  PENDING_SIGNAL: "Senal pendiente",
  EXECUTED: "Ejecutada",
  NOTIFIED: "Notificada",
  NEW: "Nuevo",
  REMOVED: "Removido",
  PLANNED: "Planificada",
  DONE: "Hecho",
  BLOCKED: "Bloqueada",
  Cumplido: "Cumplido",
  Vencido: "Vencido",
  "En ejecucion": "En ejecucion",
  Pendiente: "Pendiente"
};

export const typeLabels: Record<string, string> = {
  CORRECTIVE: "Correctivo",
  EVOLUTIONARY: "Evolutivo",
  PREVENTIVE: "Preventivo",
  EMERGENCY: "Emergencia",
  LOW: "Baja",
  MEDIUM: "Media",
  HIGH: "Alta",
  CRITICAL: "Critica",
  CODE: "Codigo",
  DOCUMENT: "Documento",
  SCRIPT: "Script",
  MODEL: "Modelo",
  CONFIGURATION: "Configuracion",
  OTHER: "Otro",
  WORK: "Trabajo",
  INTEGRATION: "Integracion",
  SUPPORT: "Soporte",
  MASTER: "Maestra",
  FUNCTIONAL: "Funcional",
  REGRESSION: "Regresion",
  FINAL_QUALITY: "Calidad final",
  SCRUM: "Scrum",
  KANBAN: "Kanban",
  RUP: "RUP",
  CASCADA: "Cascada",
  XP: "XP",
  CUSTOM: "Personalizada",
  EPIC: "Epic",
  FEATURE: "Feature",
  USER_STORY: "Historia",
  TASK: "Tarea",
  BUG: "Bug",
  ISSUE: "Issue",
  PARENT: "Padre",
  CHILD: "Hijo",
  RELATED: "Relacionado",
  PREDECESSOR: "Predecesor",
  SUCCESSOR: "Sucesor",
  GITHUB_BRANCH: "Rama GitHub",
  GITHUB_COMMIT: "Commit GitHub",
  GITHUB_PULL_REQUEST: "Pull Request GitHub",
  GITHUB_ISSUE: "Issue GitHub",
  CHANGE_REQUEST: "Solicitud de cambio",
  CHANGE_ORDER: "Orden de cambio",
  CONFIG_ITEM: "ECS",
  RELEASE: "Release",
  ANALYSIS: "Analisis",
  DESIGN: "Diseno",
  STAKEHOLDER_INTERVIEW: "Entrevista",
  REQUIREMENT_SPEC: "Requisitos",
  USE_CASE: "Caso de uso",
  ACCEPTANCE_CRITERIA: "Criterios de aceptacion",
  BACKLOG_ITEM: "Item de backlog",
  PROCESS_POLICY: "Politica de proceso",
  DOMAIN_MODEL: "Modelo de dominio",
  ARCHITECTURE_DOC: "Arquitectura",
  CLASS_DIAGRAM: "Diagrama de clases",
  SEQUENCE_DIAGRAM: "Diagrama de secuencia",
  DATA_MODEL: "Modelo de datos",
  API_CONTRACT: "Contrato API",
  UI_PROTOTYPE: "Prototipo UI",
  SOURCE_CODE: "Codigo fuente",
  DATABASE_SCRIPT: "Script BD",
  BUILD_SCRIPT: "Build script",
  CONFIGURATION_FILE: "Archivo de configuracion",
  UNIT_TEST_EVIDENCE: "Evidencia unitaria",
  QA_TEST_CASE: "Caso QA",
  RELEASE_NOTE: "Nota de version"
};

export function labelFor(value?: string | null) {
  if (!value) return "-";
  return statusLabels[value] ?? typeLabels[value] ?? value.replaceAll("_", " ");
}

export function statusTone(value?: string | null) {
  if (!value) return "neutral";
  if (["APPROVED", "PASSED", "ACCEPTED", "COMPLETED", "CLOSED", "EXECUTED", "RELEASED", "AVAILABLE", "ACTIVE", "DONE", "RESOLVED", "QA_APPROVED", "Cumplido"].includes(value)) {
    return "success";
  }
  if (["REJECTED", "FAILED", "ALIGNMENT_REJECTED", "QA_DEFECTS", "QA_REJECTED", "FORMAT_OBSERVED", "UAT_OBSERVATIONS", "CRITICAL", "LOCKED", "FORCED", "BLOCKED", "REMOVED", "Vencido"].includes(value)) {
    return "danger";
  }
  if (["HIGH", "FAST_APPROVAL", "CCB_REVIEW", "IMPACT_ANALYSIS", "FINAL_VALIDATION", "UNIT_TESTING", "QA_TESTING", "UAT", "IN_PROGRESS", "ACTIVE", "SUBMITTED", "En ejecucion"].includes(value)) {
    return "warning";
  }
  return "neutral";
}
